### ISSUE TITLE
Prevent drift within workspaces by importing all related resources

### ISSUE THREAD

**Issue by bendrucker** [TakeScoop/terraform-cloud-workspace-action#70]
The action should be able to discover all related resources (e.g., variables, team access) and remove configuration that is not specified in the action inputs. This behavior should be optional, default TBD. This allows users to detect/revert drift within workspaces managed by this action. Drift is already prevented on the workspace settings themselves, but not for related resources.

**Comment by bendrucker** [comment]
If this doesn't make v1, we'd have to put this in v2 in order to enable it by default.

**Comment by ryanwholey** [comment]
fixed by #72
